from enum import Enum


class Actors(Enum):
    FILE_MONITOR_ACTOR = "FILE_MONITOR_ACTOR"
    TASK_MONITOR_ACTOR = "TASK_MONITOR_ACTOR"
    TASK_ACTOR = "TASK_ACTOR"
    TIMER_ACTOR = "TIMER_ACTOR"
    SCHEDULER_ACTOR = "SCHEDULER_ACTOR"
